if (WIN32)
	message("ATTEMPTING TO FIND GLEW")
	set(GLEW_LIBS ${CMAKE_SOURCE_DIR}/extern/glew-2.1.0/lib/Release/x64/glew32.lib)
	set(GLEW_DLLS ${CMAKE_SOURCE_DIR}/extern/glew-2.1.0/bin/Release/x64/glew32.dll)
	set(GLEW_INCLUDE_DIRS ${CMAKE_SOURCE_DIR}/extern/glew-2.1.0/include/)
else()
	set(GLEW_LIBS "GLEW::GLEW")
endif()