if (WIN32)
	message("ATTEMPTING TO FIND GLUT")
	# set(GLUT_LIBS ${CMAKE_SOURCE_DIR}/extern/freeglut-3.2.2/lib/x64/freeglut.lib)
	# set(GLUT_DLLS ${CMAKE_SOURCE_DIR}/extern/freeglut-3.2.2/bin/x64/freeglut.lib)
	set(GLUT_INCLUDE_DIRS ${CMAKE_SOURCE_DIR}/extern/freeglut-3.2.2/include/)
else()
	set(GLUT_LIBS "GLUT::GLUT")
endif()